[package]
name = "bonelab_mod_manager"
version = "0.1.0"
authors = ["Valentine Briese <valentinegb@icloud.com>"]
edition = "2021"
description = "Syncs your Bonelab mods with your subscribed mod.io mods and keeps them up-to-date."
repository = "https://github.com/valentinegb/bonelab_mod_manager"
license = "MIT"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
modio = "0.8.0"
postcard = "1.0.4"
serde = { version = "1.0.171", features = ["derive"] }
tokio = { version = "1.29.1", features = ["full"] }
