[package]
name = "bonelab_mod_manager"
version = "0.1.1"
authors = ["Valentine Briese <valentinegb@icloud.com>"]
edition = "2021"
description = "Keeps your installed Bonelab mods synced with your subscribed mod.io mods."
repository = "https://github.com/valentinegb/bonelab_mod_manager"
license = "MIT"
keywords = ["bonelab", "mods", "mods-downloader"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.72", features = ["backtrace"] }
console = "0.15.7"
dialoguer = { version = "0.10.4", default-features = false, features = ["password"] }
futures-util = { version = "0.3.28", features = ["tokio-io"] }
indicatif = { version = "0.17.5", features = ["tokio"] }
modio = { git = "https://github.com/valentinegb/modio-rs.git", branch = "downloader-content-length" }
postcard = { version = "1.0.6", features = ["use-std"] }
serde = { version = "1.0.174", features = ["derive"] }
tokio = { version = "1.29.1", features = ["full"] }
zip = "0.6.6"

[target.'cfg(unix)'.dependencies]
keyring = "2.0.5"
