name: Rust

on:
  push:
    branches: [ "rewrite" ]
  pull_request:
    branches: [ "rewrite" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  MODIO_API_KEY: ${{ secrets.MODIO_API_KEY }}

jobs:
  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build for macOS (Intel)
      run: cargo build --release --target x86_64-apple-darwin --verbose
    - name: Build for macOS (Apple Silicon)
      run: cargo build --release --target aarch64-apple-darwin --verbose
    - name: Run tests
      run: cargo test --release --verbose
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build for Linux
      run: cargo build --release --verbose
    - name: Tar executable
      run: tar -czvf bonelab_mod_manager.tar.gz -C target/release bonelab_mod_manager
    - name: Upload Linux build artifact
      uses: actions/upload-artifact@v3
      with:
        name: bonelab_mod_manager-${{ runner.os }}
        path: bonelab_mod_manager.tar.gz
    - name: Run tests
      run: cargo test --release --verbose
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build for Windows
      run: cargo build --release --verbose
    - name: Upload Windows build artifact
      uses: actions/upload-artifact@v3
      with:
        name: bonelab_mod_manager-${{ runner.os }}
        path: target/release/bonelab_mod_manager.exe
    - name: Run tests
      run: cargo test --release --verbose
