name: Rust Build

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  MODIO_API_KEY: ${{ secrets.MODIO_API_KEY }}

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --release --verbose
      - uses: actions/upload-artifact@v3
        with:
          name: bonelab_mod_manager-${{ runner.os }}
          path: target/release/bonelab_mod_manager.exe
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build x86_64
        run: cargo build --release --target x86_64-apple-darwin --verbose
      - name: Add aarch64 target
        run: rustup target add aarch64-apple-darwin
      - name: Build aarch64
        run: cargo build --release --target aarch64-apple-darwin --verbose
      - name: Create universal executable
        run: |
          lipo \
            target/x86_64-apple-darwin/release/bonelab_mod_manager \
            target/aarch64-apple-darwin/release/bonelab_mod_manager \
            -create \
            -output "Bonelab Mod Manager Installer/Bonelab Mod Manager.app/Contents/Resources/bonelab_mod_manager"
      - name: Make Applications alias
        run: ln -s /Applications "Bonelab Mod Manager Installer"
      - name: Create DMG
        run: |
          hdiutil \
            create \
            -srcfolder "Bonelab Mod Manager Installer" \
            bonelab_mod_manager.dmg
      - uses: actions/upload-artifact@v3
        with:
          name: bonelab_mod_manager-${{ runner.os }}
          path: bonelab_mod_manager.dmg
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --release --verbose
      - name: Create TAR
        run: tar -czvf bonelab_mod_manager.tar.gz -C target/release bonelab_mod_manager
      - uses: actions/upload-artifact@v3
        with:
          name: bonelab_mod_manager-${{ runner.os }}
          path: bonelab_mod_manager.tar.gz
